# Generated by Django 4.1.7 on 2023-05-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
                ("visit_id", models.AutoField(primary_key=True, serialize=False)),
                ("writer", models.CharField(max_length=20, verbose_name="작성자")),
                ("content", models.TextField(verbose_name="내용")),
            ],
            options={"abstract": False,},
        ),
    ]
