# Generated by Django 4.1.7 on 2023-05-10 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit", old_name="visit_id", new_name="visit_id2",
        ),
    ]
