# Generated by Django 4.1.7 on 2023-05-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0002_rename_visit_id_visit_visit_id2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit", old_name="visit_id2", new_name="visit_id",
        ),
    ]
